name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/GraphQL.SQL.Builder.sln
    - name: Build
      run: dotnet build src/GraphQL.SQL.Builder.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test src/GraphQL.SQL.Builder.sln --no-build --verbosity normal --configuration Release
    - name: Publish NuGet
      run: dotnet nuget push /src/GraphQL.SQL.Builder/bin/Release/GraphQL.SQL.Builder.1.0.0.nupkg --source https://api.nuget.org/v3/index.json
        
